version: "3"
services:
  frps:
    image: stilleshan/frps:latest
    container_name: frps
    restart: always
    ports:
      - 800:800
      - 4430:4430
      - 6443:6443
      - 32877:32877
      - 32878:32878
    volumes:
      - /root/frps/frps.ini:/frp/frps.ini
    
